version: 2
# No builds - this is a library only
changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\([\w-]+\))?!?:.*'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\([\w-]+\))?!?:.*'
      order: 1
    - title: "Refactor"
      regexp: '^refactor(\([\w-]+\))?!?:.*'
      order: 2
    - title: "Build Process Updates"
      regexp: '^(build|ci)(\([\w-]+\))?!?:.*'
      order: 3
    - title: "Documentation Updates"
      regexp: '^docs(\([\w-]+\))?!?:.*'
      order: 4
    - title: "Maintenance"
      regexp: '^chore(\([\w-]+\))?!?:.*'
      order: 5
    - title: Others
      order: 999
